// SPRINT-4: checkout / order request + public response contract (version 1.2.0).
import type { CartRequest, PricedLineSnapshot, TipApplied } from "./cart";
import type { ApiErrorCode } from "./errors";

export type CreateOrderCustomer = {
  firstName: string;
  lastName: string;
  phone: string;
  email: string;
  /** Explicit boolean — never inferred from presence of a phone. */
  smsConsent: boolean;
};

/**
 * Order creation body. Prices/totals/tax must NOT appear — rejected if present.
 * `paymentToken` is a Square Web Payments SDK token (never a card number).
 * `idempotencyKey` is generated by the storefront per checkout attempt and reused on retry.
 */
export type CreateOrderRequest = {
  cart: CartRequest;
  customer: CreateOrderCustomer;
  paymentToken: string;
  idempotencyKey: string;
  customerNote?: string | null;
};

/** Returned on successful create (and idempotent replay). Includes lookupToken once. */
export type CheckoutOrderResponse = {
  id: string;
  orderNumber: string | null;
  status: string;
  paymentStatus: string;
  lookupToken: string;
  subtotalCents: number;
  taxCents: number;
  tipCents: number;
  tipRateBps: number | null;
  totalCents: number;
  taxRateBps: number;
  taxAppliedPreDiscount: boolean;
  estimatedReadyAt: string | null;
  lines: Array<{
    itemName: string;
    boardLabel: string | null;
    quantity: number;
    baseUnitPriceCents: number;
    modifierTotalCents: number;
    effectiveUnitPriceCents: number;
    lineTotalCents: number;
    selectedModifiers: PricedLineSnapshot["selectedModifiers"];
    customerNote: string | null;
  }>;
  tip: TipApplied | null;
};

/** Public status lookup — no phone, email, token, or processor fields. */
export type PublicOrderStatusResponse = {
  orderNumber: string | null;
  status: string;
  firstName: string;
  subtotalCents: number;
  taxCents: number;
  tipCents: number;
  totalCents: number;
  estimatedReadyAt: string | null;
  lines: Array<{
    itemName: string;
    boardLabel: string | null;
    quantity: number;
    effectiveUnitPriceCents: number;
    lineTotalCents: number;
    selectedModifiers: PricedLineSnapshot["selectedModifiers"];
  }>;
};

export type CheckoutBlockingCode = Extract<
  ApiErrorCode,
  | "STORE_CLOSED"
  | "STORE_NOT_ACCEPTING_ORDERS"
  | "ITEM_UNAVAILABLE"
  | "PAYMENT_DECLINED"
  | "PAYMENT_FAILED"
  | "IDEMPOTENCY_CONFLICT"
  | "VALIDATION_ERROR"
  | "NOT_FOUND"
>;
