// SPRINT-4 / SPRINT-18.3 / SPRINT-19: checkout / order request + public response contract (version 1.4.0).
import type { CartRequest, PricedLineSnapshot, TipApplied } from "./cart";
import type { ApiErrorCode } from "./errors";

export type CreateOrderCustomer = {
  firstName: string;
  lastName: string;
  phone: string;
  email: string;
  /**
   * SPRINT-17: RETIRED but still accepted. SMS was removed with Twilio, so this is never read
   * or stored. Optional so new clients can omit it; tolerated so existing ones do not break.
   */
  smsConsent?: boolean;
};

/**
 * Order creation body. Prices/totals/tax must NOT appear — rejected if present.
 * `paymentToken` is an NMI Collect.js single-use payment token (never a card number).
 * `idempotencyKey` is generated by the storefront per checkout attempt and reused on retry.
 */
export type CreateOrderRequest = {
  cart: CartRequest;
  customer: CreateOrderCustomer;
  paymentToken: string;
  /**
   * SPRINT-18.3: the ZIP on the card's billing statement, sent to the gateway for AVS and never
   * stored. Five digits, or ZIP+4 (the server keeps the first five). Optional in the contract so
   * existing clients keep working; the storefront always sends it.
   */
  billingZip?: string;
  idempotencyKey: string;
  customerNote?: string | null;
  /**
   * SPRINT-19 (additive): how the token was produced. Omitted means `card`, so existing clients
   * keep working. It does not change the sale: every method's token goes through the same request.
   */
  paymentMethod?: PaymentMethod;
  /**
   * SPRINT-19 (additive): for a wallet, the amount the wallet sheet showed the customer and they
   * authorised, exactly as it was handed to Collect.js ("12.34"). Required for a wallet, ignored
   * for a card. It is NEVER a price: the server charges its own total and refuses the sale, before
   * the gateway is called, when this differs from it. Named so it cannot be mistaken for, or pass
   * as, the forbidden client money fields (`…Cents`, `…Price`, `amount`, `total`).
   */
  walletDisplayedAmount?: string;
  /** SPRINT-19 (additive): card brand as Collect.js reported it ("visa"). Diagnostic only. */
  cardBrand?: string;
};

/** SPRINT-19: the ways a customer can produce a payment token. */
export const PAYMENT_METHODS = ["card", "apple_pay", "google_pay"] as const;
export type PaymentMethod = (typeof PAYMENT_METHODS)[number];

/** Returned on successful create (and idempotent replay). Includes lookupToken once. */
export type CheckoutOrderResponse = {
  id: string;
  orderNumber: string | null;
  status: string;
  paymentStatus: string;
  lookupToken: string;
  subtotalCents: number;
  taxCents: number;
  tipCents: number;
  tipRateBps: number | null;
  totalCents: number;
  taxRateBps: number;
  taxAppliedPreDiscount: boolean;
  estimatedReadyAt: string | null;
  lines: Array<{
    itemName: string;
    boardLabel: string | null;
    quantity: number;
    baseUnitPriceCents: number;
    modifierTotalCents: number;
    effectiveUnitPriceCents: number;
    lineTotalCents: number;
    selectedModifiers: PricedLineSnapshot["selectedModifiers"];
    customerNote: string | null;
  }>;
  tip: TipApplied | null;
};

/** Public status lookup — no phone, email, token, or processor fields. */
export type PublicOrderStatusResponse = {
  orderNumber: string | null;
  status: string;
  firstName: string;
  subtotalCents: number;
  taxCents: number;
  tipCents: number;
  totalCents: number;
  estimatedReadyAt: string | null;
  /** ISO timestamp of handover, or null while the order is still in the kitchen. */
  pickedUpAt: string | null;
  lines: Array<{
    itemName: string;
    boardLabel: string | null;
    quantity: number;
    effectiveUnitPriceCents: number;
    lineTotalCents: number;
    selectedModifiers: PricedLineSnapshot["selectedModifiers"];
  }>;
};

export type CheckoutBlockingCode = Extract<
  ApiErrorCode,
  | "STORE_CLOSED"
  | "STORE_NOT_ACCEPTING_ORDERS"
  | "ITEM_UNAVAILABLE"
  | "PAYMENT_DECLINED"
  | "PAYMENT_FAILED"
  | "PAYMENT_UNAVAILABLE"
  | "IDEMPOTENCY_CONFLICT"
  | "VALIDATION_ERROR"
  | "NOT_FOUND"
>;
